### ISSUE TITLE
Cannot uninstall / remove

### ISSUE THREAD

**Issue by anonusernam** [mjfender/goophy#6]
The Add-ons / Manage add-ons / Goophy / Remove menu sequence to uninstall Goophy is a huge Fail.  Goophy remains installed.  I have tried this multiple times, as well as in an Incognito window.

**Comment by mjfender** [comment]
Thank you for letting me know. This isn't something (the add-on uninstall process) that Google exposes to add-on developers ( https://developers.google.com/gsuite/add-ons/guides/lifecycle ). You can imagine that developers might try to prevent users from removing an add-on, if they could.

So there must be some error happening on Google's side. I am going to reach out and ask for them to look into the issue, which I was also able to reproduce in my testing.  

Goophy isn't supposed to hijack your Google Docs! :( Really sorry about the error. Will post an update when I hear back.

**Comment by mjfender** [comment]
Please add a star to this issue to help escalate it to the Google team: https://issuetracker.google.com/issues/130908576

**Comment by mjfender** [comment]
Update from Google, @anonusernam. Please let me know if this solution works for you.

--> https://issuetracker.google.com/issues/130908576

> Currently this happens when the add-on is installed in the G Suite Marketplace. **The user should also uninstall it from https://gsuite.google.com/marketplace/myapps.**
We are working on migrating all G Suite add-ons to the G Suite Marketplace, which will fix this issue.
